# Generated by Django 5.1.3 on 2024-11-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('load_value', models.FloatField()),
                ('tilt_status', models.FloatField()),
                ('distance', models.FloatField()),
                ('label', models.IntegerField()),
            ],
        ),
    ]
